name: linter
description: |
  A GitHub Action for linting (eg. Bash, Go, CloudFormation, Dockerfiles, etc)
author: jcleal

runs:
  using: docker
  image: Dockerfile

branding:
  icon: user-check
  color: yellow
