name: linter
description: |
  A GitHub Action for linting (eg. Bash, Go, CloudFormation, Dockerfiles, etc)
author: jcleal

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        docker build -t linter $GITHUB_ACTION_PATH/

    - shell: bash
      run: |
        $GITHUB_ACTION_PATH/entrypoint.sh

branding:
  icon: user-check
  color: yellow
